name: OHA Performance Test

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - 'landon/oha-perf'

jobs:
  test-oha:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: "Cache cargo"
      id: cache-cargo
      uses: "actions/cache@v4"
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        save-always: true
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Install oha
      run: cargo install oha

    - name: Install Node.js and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'yarn'

    - name: Start web server and run tests
      run: |
        cd examples/basic
        yarn install --frozen-lockfile
        
        # Start server in background
        nohup yarn start > server.log 2>&1 &
        
        # Simple sleep to allow server to start
        sleep 5
        
        # Run performance test for 5 seconds
        oha http://127.0.0.1:3000 -z 5sec --json --no-tui > oha-results.json
        
        # Kill all node processes (more reliable than pid file)
        pkill node

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: oha-results
        path: |
          examples/basic/oha-results.json
          examples/basic/server.log