name: OHA Performance Test

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - 'landon/oha-perf'

jobs:
  test-oha:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: "Cache cargo"
      id: cache-cargo
      uses: "actions/cache@v4"
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install oha
      run: cargo install oha

    - name: Install Node.js and Yarn
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'yarn'

    - name: Start web server and run tests
      run: |
        yarn install
        yarn build
        
        # Now move to examples and start server
        cd examples/basic
        yarn install
        
        # Start server in background and redirect output to log file
        yarn start > server.log 2>&1 &
        SERVER_PID=$!
        
        # Wait and check if server is running

        sleep 5
        if ! ps -p $SERVER_PID > /dev/null; then
          echo "Server failed to start"
          echo "Server logs:"
          cat server.log
          exit 1
        fi
        
        # Run performance test
        oha http://127.0.0.1:3000 -z 5sec --json --no-tui > oha-results.json || true
        
        # Kill server
        kill $SERVER_PID || true

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: oha-results
        path: |
          examples/basic/oha-results.json
          examples/basic/server.log